# file      : buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

./: {*/ -build/} \
    doc{README.md PACKAGE-README.md NEWS} \
    legal{GPLv2 LICENSE FLOSSE} \
    manifest
